GET  http://localhost:4000/api/profil?userName=hale


###
PATCH  http://localhost:4000/api/profil/rate?userName=sestra
Content-Type: application/json
Authorization: Berar eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDIxNTUwMmZmM2E3ZmJiMWRhYWM1ZWUiLCJpYXQiOjE2ODAwODA2OTZ9.AmbQxfAt3ua1mvB5ZFTbtHcl9UW-df4qNhglSpbXa7E

{
    "rate":1
}

